### PR TITLE
Arguments named "arguments" are not allowed in strict mode

### PR DESCRIPTION
**Pull request by jason-wolfe**

### CODE REVIEW

**Comment by jason-wolfe** [comment]
There's no code outside of dist/ in this repo so I'm not really sure if this is what should be happening

**Review by bjmnbraun — APPROVED** [review]
LGTM

**Comment by jason-wolfe** [comment]
Does this need to accompany a version change in package.json?

**Comment by bjmnbraun** [comment]
Let's find out? I certainly added one before but that might be unnecessary.

**Comment by bjmnbraun** [comment]
It's necessary, bumped the version number.

**Comment by jason-wolfe** [comment]
Thanks!

**Pull request merged**
